server:
  port: 8089
spring:
  application:
    name: rocketmq-producer
rocketmq:
  name-server: 101.42.254.181:8081     # rocketMq的nameServer地址
  producer:
    topic: my-topic
    group: powernode-group        # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-async-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度